#release configuration
#Sun Aug 09 15:24:10 CEST 2026
completedPhase=end-release
exec.activateProfiles=deploy-to-scijava
exec.additionalArguments=-Dgpg.skip\=true 
exec.pomFileName=pom.xml
exec.snapshotReleasePluginAllowed=false
pinExternals=false
preparationGoals=clean verify
project.dev.de.tum.nat.sdmm\:action-bar-fx=0.1.1-SNAPSHOT
project.rel.de.tum.nat.sdmm\:action-bar-fx=0.1.0
project.scm.de.tum.nat.sdmm\:action-bar-fx.connection=scm\:git\:https\://github.com/duderstadt-lab/action-bar-fx
project.scm.de.tum.nat.sdmm\:action-bar-fx.developerConnection=scm\:git\:git@github.com\:duderstadt-lab/action-bar-fx
project.scm.de.tum.nat.sdmm\:action-bar-fx.tag=HEAD
project.scm.de.tum.nat.sdmm\:action-bar-fx.url=https\://github.com/duderstadt-lab/action-bar-fx
projectVersionPolicyConfig=<projectVersionPolicyConfig>${projectVersionPolicyConfig}</projectVersionPolicyConfig>\n
projectVersionPolicyId=default
pushChanges=false
releaseStrategyId=default
remoteTagging=true
scm.branchCommitComment=@{prefix} prepare branch @{releaseLabel}
scm.commentPrefix=[maven-release-plugin] 
scm.developmentCommitComment=@{prefix} prepare for next development iteration
scm.releaseCommitComment=@{prefix} prepare release @{releaseLabel}
scm.rollbackCommitComment=@{prefix} rollback the release of @{releaseLabel}
scm.tag=action-bar-fx-0.1.0
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:https\://github.com/duderstadt-lab/action-bar-fx
